source :gemcutter

gem "haml", "2.2.20"
gem "json", "1.2.3"
gem "sinatra", "0.9.4"

group :development do
  gem "shotgun"
end

group :test do
  gem "rack-test", "0.5.3", :require => "rack/test"
  gem "rspec", "1.3.0"
  gem "test-unit", "1.2.3"
end
